---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  releaseName: lidarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: aste88
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/lidarr
      tag: latest
      pullPolicy: Always
    env:
      TZ: "Europe/London"
    podSecurityContext:
      supplementalGroups:
        - 568
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/appName: "lidarr"
          hajimari.io/enable: "true"
          hajimari.io/icon: "lidarr"
        hosts:
        - host: "lidarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "lidarr.${SECRET_DOMAIN}"
          secretName: "lidarr-tls"
        secretName: "lidarr-tls"
    hostNetwork: true
    persistence:
      config:
        enabled: true
        existingClaim: lidarr
      downloads:
        enabled: true
        existingClaim: downloads
        mountPath: /config/Downloads
      music:
        enabled: true
        existingClaim: music
        mountPath: /data/music
