---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: truecharts-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://library-charts.truecharts.org
  timeout: 3m
