---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: weaveworks-kured-charts
  namespace: flux-system
spec:
  interval: 15m
  url:  https://kubereboot.github.io/charts
  timeout: 3m
