---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  releaseName: overseerr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/overseerr
      tag: latest
      pullPolicy: Always
    env:
      TZ: "Europe/London"
    podSecurityContext:
      supplementalGroups:
      - 568
    service:
      main:
        ports:
          http:
            port: 5055
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/appName: "overseerr"
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
        hosts:
        - host: "request.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "request.${SECRET_DOMAIN}"
          secretName: "overseerr-tls"
    hostNetwork: true
