---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: latest
      pullPolicy: Always
    env:
      TZ: "Europe/London"
    podSecurityContext:
      supplementalGroups:
      - 568
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/appName: "radarr"
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip"
        hosts:
        - host: "radarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "radarr.${SECRET_DOMAIN}"
          secretName: "radarr-tls"
    hostNetwork: true
    persistence:
      config:
        enabled: true
        existingClaim: radarr
      downloads:
        enabled: true
        existingClaim: downloads
        mountPath: /config/Downloads
      movies:
        enabled: true
        existingClaim: movies
        mountPath: /movies
