---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  releaseName: sabnzbd
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sabnzbd
      tag: v3.3.1
    env:
      TZ: "Europe/London"
    podSecurityContext:
      supplementalGroups:
      - 568
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: false
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "sabnzbd.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sabnzbd.${SECRET_DOMAIN}"
          secretName: "sabnzbd-tls"
    hostNetwork: true
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd
      downloads:
        enabled: true
        existingClaim: downloads
        mountPath: /config/Downloads
