---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudDNS:
            project: "${SECRET_GCLOUD_PROJECT}"
            serviceAccountSecretRef:
              name: gcloud-sa
              key: key.json
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
