---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/apps/ha
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha
  namespace: ha
spec:
  storageClassName: local-storage
  volumeName: ha
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
