---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ha
  namespace: ha
spec:
  releaseName: ha
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truecharts.org
      chart: home-assistant
      version: 15.0.67
      sourceRef:
        kind: HelmRepository
        name: truecharts-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: tccr.io/truecharts/home-assistant
      tag: latest
      pullPolicy: Always

