---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config
  namesapce: hajimari
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
